// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdrcpflmnxhkzrlhdhda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcmNwZmxtbnhoa3pybGhkaGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDAxNTcsImV4cCI6MjA3NDMxNjE1N30.mXIxps6-OwN9bc3HK9p6b0c8_69I8w1KPiMreIAfCss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});